
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package dev.danigpaz.parser.programmingLanguageParsers.java;

/** CUP generated interface containing symbol constants. */
public interface JavaParserSym {
  /* terminals */
  public static final int IMPORT = 2;
  public static final int CLASSNAME = 28;
  public static final int CLASS = 4;
  public static final int SEMICOLON = 16;
  public static final int RBRACE = 11;
  public static final int RPAREN = 13;
  public static final int PRIVATE = 19;
  public static final int NATIVE = 27;
  public static final int LPAREN = 12;
  public static final int LBRACKET = 14;
  public static final int ANNOTATION = 9;
  public static final int LBRACE = 10;
  public static final int PUBLIC = 18;
  public static final int VOLATILE = 24;
  public static final int RBRACKET = 15;
  public static final int STATIC = 21;
  public static final int ATTVALUE = 29;
  public static final int TYPE = 30;
  public static final int IMPLEMENTS = 8;
  public static final int COMMA = 17;
  public static final int PROTECTED = 20;
  public static final int EOF = 0;
  public static final int TRANSIENT = 25;
  public static final int FINAL = 22;
  public static final int error = 1;
  public static final int ENUM = 6;
  public static final int INTERFACE = 5;
  public static final int ABSTRACT = 23;
  public static final int SYNCHRONIZED = 26;
  public static final int PACKAGE = 3;
  public static final int EXTENDS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IMPORT",
  "PACKAGE",
  "CLASS",
  "INTERFACE",
  "ENUM",
  "EXTENDS",
  "IMPLEMENTS",
  "ANNOTATION",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "SEMICOLON",
  "COMMA",
  "PUBLIC",
  "PRIVATE",
  "PROTECTED",
  "STATIC",
  "FINAL",
  "ABSTRACT",
  "VOLATILE",
  "TRANSIENT",
  "SYNCHRONIZED",
  "NATIVE",
  "CLASSNAME",
  "ATTVALUE",
  "TYPE"
  };
}

